pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "flaskapp:v1"
        APP_PATH = "${WORKSPACE}/flask-app-cicd-master/web"
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building Docker image'
                sh """
                    docker build -t ${DOCKER_IMAGE} ${APP_PATH}
                    sleep 3
                """
            }
        }

        stage('Test') {
    steps {
        echo 'Running Unit Tests with Pytest'
        // Create venv, install requirements, and run pytest
        sh '''
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pytest tests/unit_tests.py
        '''
    }
}

stage('Integration Tests') {
    steps {
        echo 'Checking if the Flask Server boots...'
        sh '''
            . venv/bin/activate
            export FLASK_APP=app.py
            flask run & 
            SLEEP_PID=$!
            sleep 5
            curl -f http://localhost:5000 || exit 1
            kill $SLEEP_PID
        '''
    }
}

        stage('Deployment Preparation') {
            steps {
                echo 'Preparing Deployment'
                sh """
                    docker rm -f flaskapp || true
                    sleep 3
                """
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying Flask App'
                sh "docker run -d --name flaskapp -p 5000:5000 ${DOCKER_IMAGE}"
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}